name: 'WPT-diff Test Runner'
description: 'Run Web Platform Tests against a proxy and collect failed results'
author: 'MercuryWorkshop'
inputs:
  location:
    description: 'Action clone location'
    required: true
  run_js_setup:
    description: 'Whether to run node/pnpm setup'
    required: false
    default: true
  artifact_name:
    description: 'Report artifact name'
    required: false
    default: "wpt-report"
  debug:
    description: ''
    required: false
    default: false
  verbose:
    description: ''
    required: false
    default: false
  wpt_max_tests:
    description: 'Maximum number of WPT tests to run'
    required: false
    default: 'all'
  under_proxy:
    description: 'Run tests under proxy'
    required: false
    default: true
  proxy_base_url:
    description: 'Base URL for WPT tests'
    required: false
    default: 'http://localhost:1337/'
  wpt_tests_base_url:
    description: 'Base URL for WPT tests'
    required: false
    default: 'http://web-platform.test:8000'
  wpt_api_base_url:
    description: 'Base URL for WPT API'
    required: false
    default: 'https://wpt.fyi'
  enable_batching:
    description: 'Enable test batching for long-running tests'
    required: false
    default: 'false'
  checkpoint_file:
    description: 'Checkpoint file path for saving/resuming test progress (only used if batching is enabled)'
    required: false
    default: ''
  resume_from:
    description: 'Resume from a previous checkpoint file (only used if batching is enabled)'
    required: false
    default: ''
  job_index:
    description: 'Current job index for splitting tests (0-based, only used if batching is enabled)'
    required: false
    default: '0'
  total_jobs:
    description: 'Total number of jobs for splitting tests (only used if batching is enabled)'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Checkout WPT
      uses: actions/checkout@v4
      with:
        repository: web-platform-tests/wpt
        path: '${{ inputs.location }}/wpt'
        submodules: recursive

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      if: '${{ inputs.run_js_setup }}'
      with:
        version: latest

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      if: '${{ inputs.run_js_setup }}'
      with:
        node-version: latest
        cache: 'pnpm'
        cache-dependency-path: '${{ inputs.location }}/pnpm-lock.yaml'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Setup WPT hosts
      shell: bash
      working-directory: '${{ inputs.location }}/wpt'
      run: |
        ./wpt make-hosts-file | sudo tee -a /etc/hosts

    - name: Install WPT-diff dependencies
      shell: bash
      working-directory: '${{ inputs.location }}'
      run: |
        pnpm install
        pnpm exec playwright install chromium

    - name: Generate validators
      shell: bash
      working-directory: '${{ inputs.location }}'
      run: |
        pnpm generate:validators

    - name: Download previous checkpoint if resuming
      if: ${{ inputs.enable_batching == 'true' && inputs.resume_from != '' }}
      uses: actions/download-artifact@v4
      with:
        name: '${{ inputs.resume_from }}'
        path: '${{ inputs.location }}'

    - name: Start WPT server
      shell: bash
      working-directory: '${{ inputs.location }}/wpt'
      run: |
        ./wpt serve --no-h2 &
        WPT_PID=$!
        echo "WPT_PID=$WPT_PID" >> $GITHUB_ENV
        sleep 10

    - name: Create WPT-Diff config
      shell: bash
      working-directory: '${{ inputs.location }}'
      run: |
        if [ "${{ inputs.wpt_max_tests }}" = "all" ]; then
          MAX_TESTS='"all"'
        else
          MAX_TESTS="${{ inputs.wpt_max_tests }}"
        fi
        
        cat > config.toml << EOF
        [debug]
        debug = ${{ inputs.debug }}
        verbose = ${{ inputs.verbose }}

        [wpt]
        max_tests = $MAX_TESTS
        under_proxy = ${{ inputs.under_proxy }}

        [wpt.urls]
        proxy_base_url = "${{ inputs.proxy_base_url }}"
        tests_base_url = "${{ inputs.wpt_tests_base_url }}"
        api_base_url = "${{ inputs.wpt_api_base_url }}"
        EOF

    - name: Run WPT-Diff tests
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: '${{ inputs.location }}'
        run: |
          export CI=true
          
          CMD="pnpm start --report wpt-report.json"
          
          if [ "${{ inputs.enable_batching }}" = "true" ]; then
            if [ "${{ inputs.checkpoint_file }}" != "" ]; then
              CMD="$CMD --checkpoint-file ${{ inputs.checkpoint_file }}"
            fi
            
            if [ "${{ inputs.resume_from }}" != "" ] && [ -f "${{ inputs.resume_from }}" ]; then
              CMD="$CMD --resume-from ${{ inputs.resume_from }}"
            fi
          fi

          $CMD

    - name: Stop WPT server
      shell: bash
      working-directory: '${{ inputs.location }}'
      run: |
        if [ ! -z "$WPT_PID" ]; then
          kill $WPT_PID || true
        fi

    - name: Upload WPT standard report
      uses: actions/upload-artifact@v4
      with:
        name: '${{ inputs.artifact_name }}'
        path: '${{ inputs.location }}/wpt-report.json'

    - name: Upload checkpoint file if created
      if: ${{ inputs.enable_batching == 'true' && inputs.checkpoint_file != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: 'checkpoint-${{ inputs.job_index }}'
        path: '${{ inputs.location }}/${{ inputs.checkpoint_file }}'