name: "WPT-diff Report Combiner"
description: "Combine WPT test report shards and perform regression checking against previous runs"
author: "MercuryWorkshop"
inputs:
  location:
    description: "Action clone location"
    required: true
  run_js_setup:
    description: "Whether to run node/pnpm setup"
    required: false
    default: true
  artifact_name:
    description: "Report artifact name"
    required: false
    default: "wpt-report"
  enable_regression_check:
    description: "Whether to run regression check against previous workflow results"
    required: false
    default: false
  github_repository:
    description: "GitHub repository for regression check"
    required: false
    default: ""
  github_token:
    description: "GitHub token for accessing previous workflow artifacts"
    required: false
    default: ""
  regression_check_workflow_name:
    description: "Workflow name to filter when looking for previous runs"
    required: false
    default: "WPT-diff Tests"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      if: ${{ inputs.run_js_setup }}
      with:
        version: latest

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      if: ${{ inputs.run_js_setup }}
      with:
        node-version: latest
        cache: pnpm
        cache-dependency-path: ${{ inputs.location }}/pnpm-lock.yaml

    - name: Install WPT-diff dependencies
      shell: bash
      working-directory: ${{ inputs.location }}
      run: pnpm install

    - name: Download shard results
      uses: actions/download-artifact@v4
      with:
        pattern: wpt-shard-results-*
        path: ./shard-results

    - name: Combine reports
      shell: bash
      working-directory: ${{ inputs.location }}
      run: pnpm combine-reports ../shard-results ../final-reports

    - name: Run regression check
      if: ${{ inputs.github_token != '' && inputs.github_repository != '' }}
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        pnpm regression-check \
          "${{ inputs.github_repository }}" \
          "${{ inputs.github_token }}" \
          "../final-reports/failed-tests.json" \
          "../final-reports/regression-fails.json" \
          "${{ inputs.regression_check_workflow_name }}"

    - name: Upload final reports
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: final-reports/
        retention-days: 90
