promise_timeout = 15

[wpt]
# number of tests to run, "all" to run all tests
max_tests = 30
# You would only disable this for testing the runner to determine if an issue is related to the SW proxy or the runner itself
under_proxy = true

[wpt.urls]
tests_base_url = "http://web-platform.test:8000"
api_base_url = "https://wpt.fyi"
