[debug]
debug = true
verbose = true

[wpt]
# number of tests to run, "all" to run all tests
max_tests = "all"
# You would only disable this for testing the runner to determine if an issue is related to the SW proxy or the runner itself
under_proxy = true

[wpt.urls]
proxy_base_url = "http://localhost:1337"
tests_base_url = "http://web-platform.test:8000"
api_base_url = "https://wpt.fyi"

[ci]
# Number of tests to complete before saving checkpoint (default: 100)
# checkpoint_interval = 100
